runtime: php72

runtime_config:
    document_root: /public

env_variables:
    ## Put production environment variables here.
    APP_KEY: base64:Dv7Aj1LXtmnR5Sk3lN7TMSUmpo0e7LIzNRXoLbsjhEQ=
    APP_STORAGE: /tmp
    VIEW_COMPILED_PATH: /tmp
    SESSION_DRIVER: cookie

    APP_NAME: PresensiStaf
    APP_ENV: local
    APP_DEBUG: true
    APP_URL: http://localhost

    LOG_CHANNEL: stack

    DB_CONNECTION: mysql
    DB_HOST: 127.0.0.1
    DB_PORT: 3306
    DB_DATABASE: PresensiStaf
    DB_USERNAME: laravel
    DB_PASSWORD: laravel
    DB_SOCKET: '/cloudsql/strategic-cacao-140701:us-central1:presensistaf'

    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    QUEUE_CONNECTION: sync
    # SESSION_DRIVER: file
    SESSION_LIFETIME: 120

    REDIS_HOST: 127.0.0.1
    REDIS_PASSWORD: null
    REDIS_PORT: 6379

    MAIL_DRIVER: smtp
    MAIL_HOST: smtp.mailtrap.io
    MAIL_PORT: 2525
    MAIL_USERNAME: null
    MAIL_PASSWORD: null
    MAIL_ENCRYPTION: null

    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_DEFAULT_REGION: us-east-1
    AWS_BUCKET:

    PUSHER_APP_ID:
    PUSHER_APP_KEY:
    PUSHER_APP_SECRET:
    PUSHER_APP_CLUSTER: mt1

    MAPS_KEY: AIzaSyA7F1ATWYrgUHfDWr5-SBLbjx3uvS-DG40
    # MAPS_KEY=AIzaSyBARGz8L-cUnnUSCPMcfXf1K9aMrU8fcdU

    MIX_PUSHER_APP_KEY: '${PUSHER_APP_KEY}'
    MIX_PUSHER_APP_CLUSTER: '${PUSHER_APP_CLUSTER}'

beta_settings:
    cloud_sql_instances: 'strategic-cacao-140701:us-central1:presensistaf'
